agentsofglory:
  - RayEnv:
      envname: RayEnv
      env:
        seed: 450
        n_envs: 1
      framestack:
        n_stack: 4
      agent:
        seed: 1450
        policy: 'MlpPolicy'
        learning_rate: 0.0007
        n_steps: 10
        gamma: 0.99
        gae_lambda: 1
        ent_coef: 0.01
        vf_coef: 0.25
        max_grad_norm: 0.5
        rms_prop_eps: 0.00001
      learn:
        total_timesteps: !!float 1e7
        log_interval: 200

 

